# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20181025_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='has_job',
            field=models.ManyToManyField(related_name='has_category', to='main_app.Job'),
        ),
    ]
