# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('main_app', '0005_auto_20181025_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owns', to='users_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='has_jobs', to='users_app.User'),
        ),
    ]
